### TASK - 6: Program to Check Whether a Number is Positive or Negative or Zero.

- Read a number A. 
- The task is to check whether A is positive, negative or zero. 

```code
Input: A = 2
Output: 2 is positive

Input: A = -554
Output: -554 is negative


Input: A = 0
Output: 0 is zero


Instructions:
    - Please write function with name checkNumber(int num) , complete the logic in it.
    - Call this function inside main()
```

### Task 7:  Program to Check Vowel or Consonant

```
Of the 26 letters in the alphabet, there are 5 vowels and 21 consonants. 
- Read a character, check if it is a vowel or consonant. 
- Vowels are ‘a’, ‘e’, ‘i’, ‘o’, and ‘u’. 
- All other characters (‘b’, ‘c’, ‘d’, ‘f’ ….) are consonants.

**EXAMPLE**

Input: x = 'c'
Output: Consonant

Input: x = 'u'
Output: Vowel
```

In [ ]:
`

### Task 8: Calculate Sum & Product of Natural Numbers
- Read a N integer from user/keyboard/console 
    - hint: scanf() 
- Write two functions
    - one calculates : sum of n natural numbers 
    - other calculates : factorial of a number.
    
```code
**EXAMPLES**
INPUT : N = 5 
OUTPUT: 
    Sum of n natural numbers upto 5 is 10
    Factorial of 5 is 125
```

### Task 9: Print multiplication table 
```
- A multiplication table is a table that shows the multiples of a number. 
- A multiplication table is created by multiplying a constant number from 1 to a given range of numbers in repetition order.
```

```code
1. Read a num and range from user 
2. print multiplication table.

hint: use for loop or while loop
```


```code

Input: 

    num = 5 
    range = 10
    

Output:
    5 * 1 = 5
    5 * 2 = 10
    5 * 3 = 15
    5 * 4 = 20
    5 * 5 = 25
    5 * 6 = 30
    5 * 7 = 35
    5 * 8 = 40
    5 * 9 = 45
    5 * 10 = 50
```

### TASK 10: Program To Check Leap Year

```code
A year is a leap year if 
    - it is a multiple of 400 and 
    - if the year is a multiple of 4 
    - but not a multiple of 100.

For example:

    2000 is a leap year
    2022 is not a leap year
    2019 is not a leap year
    
Instructions:
    - Complete the logic by writing function checkLeapYear(int year)
    - If year is leap return leap year 
    - Other wise return Not a Leap Year
```


```code
Input: year = 2000
Output: Leap Year

Input : year = 1900
Output: Not a Leap Year

```

### TASK 11: Check Whether a Number is Prime or Not

```html
A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.
```

```code
- Read a Integer check whether num is prime or not 
- If it's prime number , print "prime"
- Otherwise print , "not prime"
```


```
INPUT: num = 5 
OUTPUT : 5 is a prime no.

INPUT: num = 66
OUTPUT: 66 is not a prime no.

```

**approach**
1. using loop (Naive Approach)
2. Using Most Efficient sqrt(N)

### TASK 12: Display Prime Numbers Between Two Intervals 

Prime numbers have only 2 factors, 1 and themselves. For example, 2,3, 5, 7, 9,… are the first 5 prime numbers

```code
- Read two intervals from user say n1 , n2 
- print possible all prime numbers in between n1 and n2 
- n1 & n2 are inclusive[included]
- Write the code , by writing a function 
    displayPrimeNumbers(int n1 , int n2)
    
- Write another function , to count no of prime numbers in the given range.
    

```

```
Input: 
    num1 = 2 
    num2 = 10

Output:
    Prime numbers between 2 and 10 are: 
        2 3 5 7 
    count: 4 
    
Input:
    num1 = 1
    num2 = 100

Output: 
      prime numbers between 1 and 100 are:
        2 3 5 7 11 13 17 ...
      count: 25
        
```

### Task 13: Find Largest Element in an Array

- Given an array arr of size N, the task is to find the largest element in the given array. 


```code
    - Read Integer N from keyboard
    - Read array[n] input values from keybroad
    - write a function , to find largest element in an array 
        - if array has one element, return same as largest
        - if array is empty , return None.
        - if array has duplicate no. and more than one largest number , always return last indexed largest number.
```


```code

Input: arr[] = {10, -20, -4}
Output: 10

Input : arr[] = {20, 10, 20, 4, 100}
Output : 100

Input: arr[] = {10, 10}
Output: 10


Input: arr[] = {10, 20, 4}
Output: 20

Input : arr[] = {}
Output : None
```

### TASK 14: Second largest element in an array

- Given an array of integers,  task is to write a program that efficiently finds the second-largest element present in the array. 

```code
    - Read Integer N from keyboard
    - Read array[n] input values from keyboard
    - write a function , to find second largest element in an array
        - if size is less than 2 return "invalid input"
        
    
    
Input: arr[] = {12, 35, 1, 10, 34, 1}
Output: The second largest element is 34.

Input: arr[] = {10, 5, 10}
Output: The second largest element is 5.

Input: arr[] = {10, 10, 10}
Output: The second largest does not exist.

```

### TASK 15 : Remove All Occurrences of an Element in an Array


```code
    - Read a integer n from keyboard
    - Read a array of N values 
    - Read a element to be remove , 
        - if element exists in an array , remove all occurences, and print remanining elements of an array.
        - if element doesn't exist in an array , print all elements and "element not exist in array"
    
    

**EXAMPLES**

INPUT:

    array = {1, 2, 1, 3, 1} 
    value = 1 

OUTPUT:
    2,3
    
    
```

### TASK 16: Reverse an Array and String

```code
    - Read array of N values 
    - Read a String 
    - Write two methods 
        - one for reversing the array elements 
        - other for reversing string chars
        
        
Input  : arr[] = {1, 2, 3}
Output : arr[] = {3, 2, 1}

Input :  arr[] = {4, 5, 1, 2}
Output : arr[] = {2, 1, 5, 4}


Input  : str : "hello"
Output : olleh

Input :  str : radar
Output : radar ( palindrome) 

```

### TASK 17: Check if String is Pangram

- A pangram is a sentence containing every letter in the English Alphabet.

```code
- Given a string Str. The task is to check if it is Pangram or not. 


Input: “The quick brown fox jumps over the lazy dog” 
Output: is a Pangram 
Explanation: Contains all the characters from ‘a’ to ‘z’] 

Input: “The quick brown fox jumps over the dog”
Output: is not a Pangram 
Explanation: Doesn’t contain all the characters from ‘a’ to ‘z’, as ‘l’, ‘z’, ‘y’ are missing


```

### TASK 18:  Print the First Letter of Each Word

```code
1. Read a string from keyboard.
2. Print the first character of every Word.

Input:
    Sai Medha Ecet Koti

Output:
    S M E K 
```

### TASK 19: Remove Leading Zeros

```code
1. Read a String from keyboard , consists of 0'1 and 1's 
2. Remove leading(beginning) zero's

Input:
    str = "0001234" 
Output: 
    1234
    
    

Input:
    str = "003096026" 
Output: 
    3096026
    
    
```

### TASK 20: Printing Inverted Pyramid

```code
1. Read a integer n from keyboard
2. print following pattern


hint: use nested loops 


Input: 8
Output:

* * * * * * * * * * * * * * * 
 * * * * * * * * * * * * * 
   * * * * * * * * * * * 
     * * * * * * * * * 
       * * * * * * * 
         * * * * * 
           * * * 
             * 
             

Input: 5
Output:
    
* * * * * * * * * 
 * * * * * * * 
   * * * * * 
     * * * 
       * 

```